resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100 #100? ?? ??? ???? ????
        slidingWindowType: COUNT_BASED #?? ??
        permittedNumberOfCallsInHalfOpenState: 10 #half-open ???? ???? ?? ?
        waitDurationInOpenState: 10000 #???? ??? ??? ???? ??(ms)
        failureRateThreshold: 50 #???? ??? default 50%
        minimumNumberOfCalls: 100 #?? ???? ???? ???? ?? ??? ?? ?? ??
        recordExceptions: #???? ???? ?? ??. ?? ??? ???? ?? ??? ??? ?? ???? ??.
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignoreExceptions: #?? ?? ???? ???? ?? ?? ??
          - com.linecorp.telemedicine.liff.exception.LiffException
    instances:
      account:
        baseConfig: default
        permittedNumberOfCallsInHalfOpenState: 20
      treatment:
        baseConfig: default
      schedule:
        baseConfig: default
      pay:
        baseConfig: default
        minimumNumberOfCalls: 10
      communication:
        baseConfig: default

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always